// <auto-generated />
using ESports_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESports_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502104959_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ESports_Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Keyboard"
                        });
                });

            modelBuilder.Entity("ESports_Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Razer",
                            Description = "Ergonomic gaming mouse with high-precision 20K DPI optical sensor and customizable RGB lighting.",
                            Price = 900.0,
                            ProductName = "Razer DeathAdder V2"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "SteelSeries",
                            Description = "Mechanical gaming keyboard with adjustable actuation and OLED smart display.",
                            Price = 1800.0,
                            ProductName = "SteelSeries Apex Pro"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Logitech",
                            Description = "High-performance wired gaming headset with Blue Voice microphone technology and 7.1 surround sound.",
                            Price = 1200.0,
                            ProductName = "Logitech G Pro X"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Corsair",
                            Description = "Anti-fray cloth gaming mousepad with superior control and glide optimization for competitive play.",
                            Price = 3500.0,
                            ProductName = "Corsair MM300 Mousepad"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "HyperX",
                            Description = "Comfortable gaming headset with 53mm drivers, virtual 7.1 surround sound, and noise-canceling mic.",
                            Price = 1000.0,
                            ProductName = "HyperX Cloud II"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "ASUS",
                            Description = "Gaming mechanical keyboard with ROG RX optical switches, RGB lighting, and IP57 water resistance.",
                            Price = 1300.0,
                            ProductName = "ASUS ROG Strix Scope RX"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
